# Pizza API

## To use these HTTP endpoint install the REST Client plugin in VSCode.

### Get all the Pizzas from the API

GET https://pizza-api.projectcodex.net/api/pizzas

### Create a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=kimmie-78


### Get a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/kv4xr0kv44/get

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
	"cart_code" : "kv4xr0kv44",
	"pizza_id" : 3
}

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
	"cart_code" : "kv4xr0kv44",
	"pizza_id" : 11
}

### Remove a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
content-type: application/json

{
	"cart_code" : "kv4xr0kv44",
	"pizza_id" : 3
}

### GET all the carts for a given user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/kimmie-78

### GET all the active carts for a user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/Lindani/active


### Pay for a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/pay	
content-type: application/json

{
	"cart_code" : "kv4xr0kv44",
	"amount" : 200
}